FROM siddhantbh/gridnode-ml-base:latest

USER root

RUN pip install --no-cache-dir \
    torch==2.2.0+cu121 \
    torchvision==0.17.0+cu121 \
    --extra-index-url https://download.pytorch.org/whl/cu121

USER $NB_UID